# Generated by Django 2.2.2 on 2021-09-28 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ichan', '0002_auto_20210928_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=250, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name_plural': 'comment',
            },
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'verbose_name_plural': 'thread'},
        ),
        migrations.RemoveField(
            model_name='thread',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='thread',
            name='exp',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='説明文'),
        ),
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=40, null=True, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ichan.Thread', verbose_name='スレッド'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
