# Generated by Django 2.2.2 on 2021-09-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicethread',
            name='desc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='説明文'),
        ),
    ]
