# Generated by Django 2.2.2 on 2021-09-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_board', '0002_nicethread_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nicecomments',
            name='text',
            field=models.TextField(max_length=250, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='nicethread',
            name='desc',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='説明文'),
        ),
    ]
