# Generated by Django 2.2.2 on 2021-09-26 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nice_board', '0003_auto_20210926_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NiceComments',
            new_name='NiceComment',
        ),
    ]
