# Generated by Django 2.2.2 on 2021-09-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_board', '0004_auto_20210927_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicecomment',
            name='ban',
            field=models.BooleanField(default=False, verbose_name='コメントアウト'),
        ),
        migrations.AddField(
            model_name='nicethread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='nicecomment',
            name='text',
            field=models.TextField(max_length=250, null=True, verbose_name='コメント'),
        ),
    ]
