# Generated by Django 2.2.2 on 2021-09-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice_board', '0005_auto_20210929_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nicecomment',
            name='text',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='コメント'),
        ),
    ]
